"""empty message

Revision ID: 5fe907e8abae
Revises: 0b0827d33561
Create Date: 2020-06-30 09:43:04.886218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fe907e8abae'
down_revision = '0b0827d33561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_update',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_update',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
